#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /root/agent.sh
    procd_set_param respawn # Reinicia el script si falla
    procd_set_param stdout 1 # Manda los logs al sistema (logread)
    procd_set_param stderr 1
    procd_close_instance
}