#!/bin/sh
set -eu

expression=""
while [ "$#" -gt 0 ]; do
    if [ "$1" = "-e" ]; then
        expression="$2"
        shift 2
    else
        shift
    fi
done

case "$expression" in
    @.operation_id) jq -r '.operation_id // empty' ;;
    @.change_set_id) jq -r '.change_set_id // empty' ;;
    @.device_id) jq -r '.device_id // empty' ;;
    @.plan_hash) jq -r '.plan_hash // empty' ;;
    @.generation) jq -r '.generation // empty' ;;
    @.state) jq -r '.state // empty' ;;
    @.config) jq -r '.config // empty' ;;
    @.config.apply_change_set) jq -c '.config.apply_change_set // empty' ;;
    @.confirmation_policy) jq -r '.confirmation_policy // empty' ;;
    '@.commands[@]') jq -c '.commands[]?' ;;
    '@.commands') jq -c '.commands // empty' ;;
    '@.operations[@]') jq -c '.operations[]?' ;;
    '@.operations[0].operation_id') jq -r '.operations[0].operation_id // empty' ;;
    '@.operations[0].config') jq -r '.operations[0].config // empty' ;;
    '@.operations[0].observed_state_hash') jq -r '.operations[0].observed_state_hash // empty' ;;
    '@.operations[0].commands') jq -c '.operations[0].commands // empty' ;;
    @.operations\[*\].operation_id)
        index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        jq -r ".operations[$index].operation_id // empty"
        ;;
    @.operations\[*\].config)
        index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        jq -r ".operations[$index].config // empty"
        ;;
    @.operations\[*\].commands)
        index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        jq -c ".operations[$index].commands // empty"
        ;;
    @.operations\[*\].commands\[@\])
        index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        jq -c ".operations[$index].commands[]?"
        ;;
    @.operations\[*\].observed_state_hash)
        index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        jq -r ".operations[$index].observed_state_hash // empty"
        ;;
    @.operations\[*\].health_checks)
        index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        jq -c ".operations[$index].health_checks // empty"
        ;;
    @.operations\[*\].commands\[*\].action)
        operation_index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        command_index=$(printf '%s' "$expression" | sed -n 's/.*commands\[\([0-9]*\)\].*/\1/p')
        jq -r ".operations[$operation_index].commands[$command_index].action // empty" ;;
    @.operations\[*\].commands\[*\].config)
        operation_index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        command_index=$(printf '%s' "$expression" | sed -n 's/.*commands\[\([0-9]*\)\].*/\1/p')
        jq -r ".operations[$operation_index].commands[$command_index].config // empty" ;;
    @.operations\[*\].commands\[*\].section)
        operation_index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        command_index=$(printf '%s' "$expression" | sed -n 's/.*commands\[\([0-9]*\)\].*/\1/p')
        jq -r ".operations[$operation_index].commands[$command_index].section // empty" ;;
    @.operations\[*\].commands\[*\].option)
        operation_index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        command_index=$(printf '%s' "$expression" | sed -n 's/.*commands\[\([0-9]*\)\].*/\1/p')
        jq -r ".operations[$operation_index].commands[$command_index].option // empty" ;;
    @.operations\[*\].commands\[*\].value)
        operation_index=$(printf '%s' "$expression" | sed -n 's/.*operations\[\([0-9]*\)\].*/\1/p')
        command_index=$(printf '%s' "$expression" | sed -n 's/.*commands\[\([0-9]*\)\].*/\1/p')
        jq -r ".operations[$operation_index].commands[$command_index].value // empty" ;;
    @.commands\[*\].action)
        index=$(printf '%s' "$expression" | tr -cd '0-9')
        jq -r ".commands[$index].action // empty"
        ;;
    @.commands\[*\].config)
        index=$(printf '%s' "$expression" | tr -cd '0-9')
        jq -r ".commands[$index].config // empty"
        ;;
    @.commands\[*\].section)
        index=$(printf '%s' "$expression" | tr -cd '0-9')
        jq -r ".commands[$index].section // empty"
        ;;
    @.commands\[*\].option)
        index=$(printf '%s' "$expression" | tr -cd '0-9')
        jq -r ".commands[$index].option // empty"
        ;;
    @.commands\[*\].value)
        index=$(printf '%s' "$expression" | tr -cd '0-9')
        jq -r ".commands[$index].value // empty"
        ;;
    '@.health_checks[@]') jq -r '.health_checks[]?' ;;
    @.health_checks) jq -c '.health_checks // empty' ;;
    @.health_checks\[*\])
        index=$(printf '%s' "$expression" | tr -cd '0-9')
        jq -r ".health_checks[$index] // empty"
        ;;
    *) exit 1 ;;
esac
