package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"openwrt-controller/internal/database"
)

// UciRestartMap maps uci config namespace to the specific init.d service that should be restarted
var UciRestartMap = map[string]string{
	"network":  "/etc/init.d/network restart",
	"wireless": "wifi",
	"dhcp":     "/etc/init.d/dnsmasq restart",
	"firewall": "/etc/init.d/firewall restart",
	"system":   "/etc/init.d/system restart",
	"dropbear": "/etc/init.d/dropbear restart",
	"uhttpd":   "/etc/init.d/uhttpd restart",
	"openvpn":  "/etc/init.d/openvpn restart",
}

// GetUciHandler retrieves the current configuration using `ubus call uci get`
// which directly yields structured JSON ready for the frontend.
func GetUciHandler(w http.ResponseWriter, r *http.Request) {
	deviceID := r.PathValue("device_id")
	config := r.URL.Query().Get("config")

	if config == "" {
		http.Error(w, `{"error": "missing config parameter"}`, http.StatusBadRequest)
		return
	}

	// Fetch via ubus
	cmd := fmt.Sprintf("ubus call uci get '{\"config\": \"%s\"}'", config)
	out, err := runSSHCommand(deviceID, cmd)
	if err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]interface{}{
			"error": err.Error(),
			"raw":   out,
		})
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write([]byte(out)) // ubus already returns JSON
}

// PutUciHandler receives a list of UCI commands (set, delete, add_list) generated by the frontend,
// runs them in a transaction with rollback capability and restarts the related service.
func PutUciHandler(w http.ResponseWriter, r *http.Request) {
	deviceID := r.PathValue("device_id")
	config := r.URL.Query().Get("config")
	username := GetUsernameFromReq(r)

	if config == "" {
		http.Error(w, `{"error": "missing config parameter"}`, http.StatusBadRequest)
		return
	}

	var payload struct {
		Commands []string `json:"commands"`
	}

	if !readBody(w, r, &payload) {
		return
	}

	var sb strings.Builder
	for _, c := range payload.Commands {
		// Prevent dangerous injection by ensuring all begin with uci and single quotes
		if !strings.HasPrefix(strings.TrimSpace(c), "uci ") {
			// Skip or sanitize
			continue
		}
		sb.WriteString(c)
		sb.WriteString("\n")
	}
	sb.WriteString(fmt.Sprintf("uci commit %s\n", config))

	restartCmd, ok := UciRestartMap[config]
	if !ok {
		restartCmd = "" // Unmapped configs don't auto-restart
	} else {
		restartCmd = restartCmd + " && logger -t uci_ops '" + config + " restarted'"
	}

	// Build the rollback script for general UCI
	script := fmt.Sprintf(`#!/bin/sh
set -e

logger -t uci_ops "UCI_OPS: starting config push for %s"

# Backup
uci export %s > /tmp/uci_ops_bak.conf 2>/dev/null || true

rollback() {
  logger -t uci_ops "UCI_OPS: ERROR — rolling back %s"
  uci import %s < /tmp/uci_ops_bak.conf 2>/dev/null || true
  uci commit %s
  exit 1
}
trap rollback ERR

# Apply changes
%s

# Validation
uci show %s > /dev/null 2>&1 || { logger -t uci_ops "validation failed"; rollback; }

# Autorestart
%s

logger -t uci_ops "UCI_OPS: push complete for %s"
exit 0
`, config, config, config, config, config, sb.String(), config, restartCmd, config)

	// Execute via SSH Script
	out, err := runSSHScript(deviceID, script)
	
	if err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{
			"error":  err.Error(),
			"output": out,
		})
		return
	}

	// Audit Log
	database.InsertAuditLog(username, "UCI_OPS_PUSH", "DEVICE", deviceID,
		fmt.Sprintf("Pushed %d UCI commands to namespace: %s", len(payload.Commands), config), r.RemoteAddr)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{
		"status": "success",
		"output": out,
	})
}
